PORTNAME=	libmixed
DISTVERSION=	2.0-93
DISTVERSIONSUFFIX=	-g72b945d
CATEGORIES=	audio

MAINTAINER=	shamaz.mazum@gmail.com
COMMENT=	Library for real-time audio processing pipelines

LICENSE=	ZLIB
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cmake

USE_GITHUB=	yes
GH_ACCOUNT=	Shirakumo

.include <bsd.port.mk>
