PORTNAME=	kandria-libs
DISTVERSION=	0.1
CATEGORIES=	games

MAINTAINER=	shamaz.mazum@gmail.com
COMMENT=	C libraries used for Kandria
WWW=		https://github.com/Shirakumo/kandria

USES=		metaport

RUN_DEPENDS=	stb_vorbis>0:audio/stb_vorbis \
		libmixed>0:audio/libmixed \
		glfw>0:graphics/glfw

.include <bsd.port.mk>
