PORTNAME=	nss_zerodns
DISTVERSION=	1.1
PORTREVISION=	2
CATEGORIES=	dns

MAINTAINER=	shamaz.mazum@gmail.com
COMMENT=	NSS module for ZeroDNS

LICENSE=	LGPL21+
LICENSE_FILE=	${WRKSRC}/LICENSE

LIB_DEPENDS=	libzmq.so:net/libzmq4

USES=		cmake
USE_GITHUB=	yes
GH_ACCOUNT=	shamazmazum
GH_PROJECT=	nss-zero-dns
GH_TAGNAME=	d73d612

.include <bsd.port.mk>
