PORTNAME=	program-map
DISTVERSION=	0.1
CATEGORIES=	devel
MAINTAINER=	shamaz.mazum@gmail.com
COMMENT=	Helper library for mapping OpenCL programs

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cmake
USE_GITHUB=	yes
GH_ACCOUNT=	shamazmazum
GH_TAGNAME=	v0.1

.include <bsd.port.mk>
