PORTNAME=	program-map
DISTVERSIONPREFIX=v
DISTVERSION=	0.2
CATEGORIES=	devel

MAINTAINER=	shamaz.mazum@gmail.com
COMMENT=	Helper library for mapping OpenCL programs

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cmake
USE_GITHUB=	yes
GH_ACCOUNT=	shamazmazum

.include <bsd.port.mk>
