PORTNAME=	libfixposix
DISTVERSION=	0.4.3
CATEGORIES=	devel
MAINTAINER=	shamaz.mazum@gmail.com
COMMENT=	Thin wrapper over POSIX syscalls

#LICENSE=	BSD
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		autoreconf gmake libtool pkgconfig
USE_GITHUB=	yes
GH_ACCOUNT=	sionescu
GH_TAGNAME=	v0.4.3
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
